import { getOverride } from './overrideStore';

export const tooltips = {
  get skipToStart() { return getOverride('tooltips.skipToStart') ?? "Skip to start"; },
  get prevAnnotation() { return getOverride('tooltips.prevAnnotation') ?? "Previous annotation (Cmd+←  or  ;)"; },
  get nextAnnotation() { return getOverride('tooltips.nextAnnotation') ?? "Next annotation (Cmd+→  or  ')"; },
  get skipToEnd() { return getOverride('tooltips.skipToEnd') ?? "Skip to end"; },
  get lockPlayhead() { return getOverride('tooltips.lockPlayhead') ?? "Lock/Unlock Playhead (C)"; },
  get jumpToTime() { return getOverride('tooltips.jumpToTime') ?? "Jump to time"; },
  editSelection: (label: string) => `Edit selection ${label}`,
  setSelection: (label: string) => `Set selection ${label}`,
  get filterDisabledByMode() { return getOverride('tooltips.filterDisabledByMode') ?? "Audio filters not available in Fast mode"; },
  get filterTool() { return getOverride('tooltips.filterTool') ?? "Ready filter tool (Shift+F)"; },
  get resetSpeed() { return getOverride('tooltips.resetSpeed') ?? "Return to 1.0× (R)"; },
  get restoreSpeed() { return getOverride('tooltips.restoreSpeed') ?? "Toggle playback rate (R)"; },
  get setSpeed() { return getOverride('tooltips.setSpeed') ?? "Click to set playback speed"; },
  get buzzdetectPanel() { return getOverride('tooltips.buzzdetectPanel') ?? "buzzdetect activations panel"; },
  get spectrogramSettings() { return getOverride('tooltips.spectrogramSettings') ?? "Spectrogram Settings"; },
  get restartAudio() { return getOverride('tooltips.restartAudio') ?? "Restart Audio"; },
  get setupSync() { return getOverride('tooltips.setupSync') ?? "How to set up a project that syncs to GitHub"; },
  get relinkProject() { return getOverride('tooltips.relinkProject') ?? "Find this project's folder on disk and re-link it"; },
  get projectSettings() { return getOverride('tooltips.projectSettings') ?? "Project settings"; },
  get unlinkProject() { return getOverride('tooltips.unlinkProject') ?? "Unlink project"; },
  get openDataFolder() { return getOverride('tooltips.openDataFolder') ?? "Open SeeNote’s internal data folder"; },
  get keepSeeNoteName() { return getOverride('tooltips.keepSeeNoteName') ?? "Keep SeeNote's name (rewrites .seenote/settings.json)"; },
  get useFolderName() { return getOverride('tooltips.useFolderName') ?? "Use the name from the folder's .seenote/settings.json"; },
  get annotationToolSettings() { return getOverride('tooltips.annotationToolSettings') ?? "Annotation Tool Settings"; },
  get stopExample() { return getOverride('tooltips.stopExample') ?? "Stop example"; },
  get playExample() { return getOverride('tooltips.playExample') ?? "Play example clip"; },
  get editTool() { return getOverride('tooltips.editTool') ?? "Edit tool"; },
  get deleteTool() { return getOverride('tooltips.deleteTool') ?? "Delete tool"; },
  get startColor() { return getOverride('tooltips.startColor') ?? "Drag to change start color · right-click for a custom color"; },
  get endColor() { return getOverride('tooltips.endColor') ?? "Drag to change end color · right-click for a custom color"; },
  get toggleZoom() { return getOverride('tooltips.toggleZoom') ?? "Toggle zoom (Z)"; },
  get marqueeZoom() { return getOverride('tooltips.marqueeZoom') ?? "Marquee zoom — drag a box on the video to zoom into it"; },
  get zoomIn() { return getOverride('tooltips.zoomIn') ?? "Zoom in"; },
  get zoomOut() { return getOverride('tooltips.zoomOut') ?? "Zoom out"; },
  get resetZoom() { return getOverride('tooltips.resetZoom') ?? "Reset zoom"; },
  get setupSyncedProject() { return getOverride('tooltips.setupSyncedProject') ?? "How to set up a synced project"; },
  get previewVolume() { return getOverride('tooltips.previewVolume') ?? "Preview volume (loudness-normalized)"; },
  get editAnnotationName() { return getOverride('tooltips.editAnnotationName') ?? "Edit annotation name"; },
  get copyLogs() { return getOverride('tooltips.copyLogs') ?? "Copy logs"; },
  get showFileTree() { return getOverride('tooltips.showFileTree') ?? "Show file tree"; },
  get backToRoot() { return getOverride('tooltips.backToRoot') ?? "Back to root"; },
  get upOneFolder() { return getOverride('tooltips.upOneFolder') ?? "Up one folder"; },
  get refreshFileList() { return getOverride('tooltips.refreshFileList') ?? "Refresh files"; },
  get collapseAll() { return getOverride('tooltips.collapseAll') ?? "Collapse all"; },
  get expandAll() { return getOverride('tooltips.expandAll') ?? "Expand all"; },
  get play() { return getOverride('tooltips.play') ?? "Play"; },
  get pause() { return getOverride('tooltips.pause') ?? "Pause"; },
  get backToProjects() { return getOverride('tooltips.backToProjects') ?? "Back to projects"; },
  get helpGuide() { return getOverride('tooltips.helpGuide') ?? "Help Guide (F1)"; },
  get keyboardShortcuts() { return getOverride('tooltips.keyboardShortcuts') ?? "Keyboard Shortcuts"; },
  get expandVideoPanel() { return getOverride('tooltips.expandVideoPanel') ?? "Expand video panel"; },
  get syncing() { return getOverride('tooltips.syncing') ?? "Syncing…"; },
  get syncIdle() { return getOverride('tooltips.syncIdle') ?? "Sync annotations"; },
  get syncUnpushed() { return getOverride('tooltips.syncUnpushed') ?? "You have unsynced annotations"; },
  get syncUnpulled() { return getOverride('tooltips.syncUnpulled') ?? "New annotations are available to download"; },
  get syncWithMessage() { return getOverride('tooltips.syncWithMessage') ?? "Sync with a commit message…"; },
  get buzzdetectSettings() { return getOverride('tooltips.buzzdetectSettings') ?? "buzzdetect settings"; },
  get importToolsDir() { return getOverride('tooltips.importToolsDir') ?? "Pick a directory of {label}/ folders of audio clips; clips are copied in as examples and tools are created for new labels"; },
  get showAllFiles() { return getOverride('tooltips.showAllFiles') ?? "Showing: all files"; },
  get showingUnannotated() { return getOverride('tooltips.showingUnannotated') ?? "Showing: unannotated only"; },
  get showingAnnotated() { return getOverride('tooltips.showingAnnotated') ?? "Showing: annotated only"; },
  get switchToSorted() { return getOverride('tooltips.switchToSorted') ?? "Enter sorted view"; },
  get shuffleQueue() { return getOverride('tooltips.shuffleQueue') ?? "Enter Shuffle Mode"; },
};
