import { getOverride } from './overrideStore';

export const tooltips = {
  get skipToStart() { return getOverride('tooltips.skipToStart') ?? "Skip to start"; },
  get prevAnnotation() { return getOverride('tooltips.prevAnnotation') ?? "Previous annotation (Cmd+←  or  ;)"; },
  get nextAnnotation() { return getOverride('tooltips.nextAnnotation') ?? "Next annotation (Cmd+→  or  ')"; },
  get skipToEnd() { return getOverride('tooltips.skipToEnd') ?? "Skip to end"; },
  get lockPlayhead() { return getOverride('tooltips.lockPlayhead') ?? "Lock playhead to center (C)"; },
  get jumpToTime() { return getOverride('tooltips.jumpToTime') ?? "Click to jump to time"; },
  editSelection: (label: string) => `Edit selection ${label}`,
  setSelection: (label: string) => `Set selection ${label}`,
  get filterDisabledByMode() { return getOverride('tooltips.filterDisabledByMode') ?? "Audio filters not available in Fast mode"; },
  get filterTool() { return getOverride('tooltips.filterTool') ?? "Filter tool (Shift+F)"; },
  get resetSpeed() { return getOverride('tooltips.resetSpeed') ?? "Click to reset to 1× (click text to set custom speed)"; },
  get restoreSpeed() { return getOverride('tooltips.restoreSpeed') ?? "Click to restore last speed"; },
  get setSpeed() { return getOverride('tooltips.setSpeed') ?? "Click to set playback speed"; },
  get buzzdetectPanel() { return getOverride('tooltips.buzzdetectPanel') ?? "buzzdetect activations panel"; },
  get spectrogramSettings() { return getOverride('tooltips.spectrogramSettings') ?? "Spectrogram Settings"; },
  get restartAudio() { return getOverride('tooltips.restartAudio') ?? "Restart Audio"; },
  get setupSync() { return getOverride('tooltips.setupSync') ?? "How to set up a project that syncs to GitHub"; },
  get relinkProject() { return getOverride('tooltips.relinkProject') ?? "Find this project's folder on disk and re-link it"; },
  get projectSettings() { return getOverride('tooltips.projectSettings') ?? "Project settings"; },
  get unlinkProject() { return getOverride('tooltips.unlinkProject') ?? "Unlink project"; },
  get openDataFolder() { return getOverride('tooltips.openDataFolder') ?? "Open the folder where projects are stored"; },
  get keepSeeNoteName() { return getOverride('tooltips.keepSeeNoteName') ?? "Keep SeeNote's name (rewrites .seenote/settings.json)"; },
  get useFolderName() { return getOverride('tooltips.useFolderName') ?? "Use the name from the folder's .seenote/settings.json"; },
  get annotationToolSettings() { return getOverride('tooltips.annotationToolSettings') ?? "Annotation Tool Settings"; },
  get stopExample() { return getOverride('tooltips.stopExample') ?? "Stop example"; },
  get playExample() { return getOverride('tooltips.playExample') ?? "Play example clip"; },
  get editTool() { return getOverride('tooltips.editTool') ?? "Edit tool"; },
  get deleteTool() { return getOverride('tooltips.deleteTool') ?? "Delete tool"; },
  get startColor() { return getOverride('tooltips.startColor') ?? "Drag to change start color · right-click for a custom color"; },
  get endColor() { return getOverride('tooltips.endColor') ?? "Drag to change end color · right-click for a custom color"; },
  get toggleZoom() { return getOverride('tooltips.toggleZoom') ?? "Toggle zoom (Z)"; },
  get marqueeZoom() { return getOverride('tooltips.marqueeZoom') ?? "Marquee zoom — drag a box on the video to zoom into it"; },
  get zoomIn() { return getOverride('tooltips.zoomIn') ?? "Zoom in"; },
  get zoomOut() { return getOverride('tooltips.zoomOut') ?? "Zoom out"; },
  get resetZoom() { return getOverride('tooltips.resetZoom') ?? "Reset zoom"; },
  get setupSyncedProject() { return getOverride('tooltips.setupSyncedProject') ?? "How to set up a synced project"; },
};
