import { getOverride } from './overrideStore';
import { formatModKey } from '../utils/platform';

export const tooltips = {
  get skipToStart() { return formatModKey(getOverride('tooltips.skipToStart') ?? "Skip to start ({mod}+←)"); },
  get prevAnnotation() { return getOverride('tooltips.prevAnnotation') ?? "Previous annotation (Alt+←)"; },
  get nextAnnotation() { return getOverride('tooltips.nextAnnotation') ?? "Next annotation (Alt+→)"; },
  get skipToEnd() { return formatModKey(getOverride('tooltips.skipToEnd') ?? "Skip to end ({mod}+→)"); },
  get lockPlayhead() { return getOverride('tooltips.lockPlayhead') ?? "Lock/Unlock Playhead (C)"; },
  get jumpToTime() { return getOverride('tooltips.jumpToTime') ?? "Jump to time"; },
  get timeUnitSeconds() { return getOverride('tooltips.timeUnitSeconds') ?? "Show running time in seconds"; },
  get timeUnitHms() { return getOverride('tooltips.timeUnitHms') ?? "Show running time as hours/minutes/seconds"; },
  get timeUnitDatetime() { return getOverride('tooltips.timeUnitDatetime') ?? "Show times as wall-clock datetimes, from the timestamp in the filename"; },
  get timeUnitDatetimeUnavailable() { return getOverride('tooltips.timeUnitDatetimeUnavailable') ?? "This filename carries no timestamp SeeNote can read — set a Filename Timestamp format in project settings"; },
  editSelection: (label: string) => `Edit selection ${label}`,
  setSelection: (label: string) => `Set selection ${label}`,
  get filterDisabledByMode() { return getOverride('tooltips.filterDisabledByMode') ?? "Audio filters not available in Fast mode"; },
  get filterTool() { return getOverride('tooltips.filterTool') ?? "Ready filter tool (Shift+F)"; },
  get resetSpeed() { return getOverride('tooltips.resetSpeed') ?? "Return to 1.0× (R)"; },
  get restoreSpeed() { return getOverride('tooltips.restoreSpeed') ?? "Toggle playback rate (R)"; },
  get setSpeed() { return getOverride('tooltips.setSpeed') ?? "Click to set playback speed"; },
  get filterStrength() { return getOverride('tooltips.filterStrength') ?? "Adjust filter strength (F to toggle)"; },
  get buzzdetectPanel() { return getOverride('tooltips.buzzdetectPanel') ?? "buzzdetect activations panel"; },
  get spectrogramSettings() { return getOverride('tooltips.spectrogramSettings') ?? "Spectrogram Settings"; },
  get resetFreqMin() { return getOverride('tooltips.resetFreqMin') ?? "Reset to 0 Hz"; },
  get resetFreqMax() { return getOverride('tooltips.resetFreqMax') ?? "Reset to nyquist limit"; },
  get restartAudio() { return getOverride('tooltips.restartAudio') ?? "Restart Audio"; },
  get setupSync() { return getOverride('tooltips.setupSync') ?? "Instructions for setting up GitHub-synced annotations"; },
  get relinkProject() { return getOverride('tooltips.relinkProject') ?? "Find this project's folder on disk and re-link it"; },
  get projectSettings() { return getOverride('tooltips.projectSettings') ?? "Project settings"; },
  get appSettings() { return getOverride('tooltips.appSettings') ?? "Application settings"; },
  get unlinkProject() { return getOverride('tooltips.unlinkProject') ?? "Unlink project"; },
  get unlinkFile() { return getOverride('tooltips.unlinkFile') ?? "Remove from Recent"; },
  get openDataFolder() { return getOverride('tooltips.openDataFolder') ?? "Open SeeNote’s internal data folder"; },
  get keepSeeNoteName() { return getOverride('tooltips.keepSeeNoteName') ?? "Keep SeeNote's name (rewrites .seenote/settings.json)"; },
  get useFolderName() { return getOverride('tooltips.useFolderName') ?? "Use the name from the folder's .seenote/settings.json"; },
  get annotationToolSettings() { return getOverride('tooltips.annotationToolSettings') ?? "Annotation Tool Settings"; },
  get findLabel() { return getOverride('tooltips.findLabel') ?? "Find Label"; },
  get stopExample() { return getOverride('tooltips.stopExample') ?? "Stop example"; },
  get playExample() { return getOverride('tooltips.playExample') ?? "Play example clip"; },
  get editTool() { return getOverride('tooltips.editTool') ?? "Edit tool"; },
  get deleteTool() { return getOverride('tooltips.deleteTool') ?? "Delete tool"; },
  get startColor() { return getOverride('tooltips.startColor') ?? "Drag to change start color · right-click for a custom color"; },
  get endColor() { return getOverride('tooltips.endColor') ?? "Drag to change end color · right-click for a custom color"; },
  get toggleZoom() { return getOverride('tooltips.toggleZoom') ?? "Toggle zoom (Z)"; },
  get marqueeZoom() { return getOverride('tooltips.marqueeZoom') ?? "Marquee zoom — drag a box on the video to zoom into it"; },
  get zoomIn() { return getOverride('tooltips.zoomIn') ?? "Zoom in"; },
  get zoomOut() { return getOverride('tooltips.zoomOut') ?? "Zoom out"; },
  get resetZoom() { return getOverride('tooltips.resetZoom') ?? "Reset zoom"; },
  get brightness() { return getOverride('tooltips.brightness') ?? "Brightness"; },
  get contrast() { return getOverride('tooltips.contrast') ?? "Contrast"; },
  get resetAdjust() { return getOverride('tooltips.resetAdjust') ?? "Reset to 100%"; },
  get setupSyncedProject() { return getOverride('tooltips.setupSyncedProject') ?? "Instructions for setting up GitHub-synced annotations"; },
  get previewVolume() { return getOverride('tooltips.previewVolume') ?? "Preview volume (loudness-normalized)"; },
  get editAnnotationName() { return getOverride('tooltips.editAnnotationName') ?? "Edit annotation name"; },
  get copyLogs() { return getOverride('tooltips.copyLogs') ?? "Copy logs"; },
  get showFileTree() { return getOverride('tooltips.showFileTree') ?? "Show file tree"; },
  get backToRoot() { return getOverride('tooltips.backToRoot') ?? "Back to root"; },
  get upOneFolder() { return getOverride('tooltips.upOneFolder') ?? "Up one folder"; },
  get refreshFileList() { return getOverride('tooltips.refreshFileList') ?? "Refresh files"; },
  get collapseAll() { return getOverride('tooltips.collapseAll') ?? "Collapse all"; },
  get expandAll() { return getOverride('tooltips.expandAll') ?? "Expand all"; },
  get play() { return getOverride('tooltips.play') ?? "Play"; },
  get pause() { return getOverride('tooltips.pause') ?? "Pause"; },
  get backToProjects() { return getOverride('tooltips.backToProjects') ?? "Back to projects"; },
  get helpGuide() { return getOverride('tooltips.helpGuide') ?? "Help Guide (F1)"; },
  get keyboardShortcuts() { return getOverride('tooltips.keyboardShortcuts') ?? "Keyboard Shortcuts"; },
  get expandVideoPanel() { return getOverride('tooltips.expandVideoPanel') ?? "Expand video panel"; },
  get syncing() { return getOverride('tooltips.syncing') ?? "Syncing…"; },
  get syncIdle() { return getOverride('tooltips.syncIdle') ?? "Sync annotations"; },
  get syncUnpushed() { return getOverride('tooltips.syncUnpushed') ?? "You have unsynced annotations"; },
  get syncUnpulled() { return getOverride('tooltips.syncUnpulled') ?? "New annotations are available to download"; },
  get syncWithMessage() { return getOverride('tooltips.syncWithMessage') ?? "Sync with a commit message…"; },
  get buzzdetectYAxisReset() { return getOverride('tooltips.buzzdetectYAxisReset') ?? "Reset to auto-calculated range"; },
  get buzzdetectBinWidthReset() { return getOverride('tooltips.buzzdetectBinWidthReset') ?? "Reset to auto-calculated bin width"; },
  get buzzdetectNeuronColor() { return getOverride('tooltips.buzzdetectNeuronColor') ?? "Change this neuron's color"; },
  get buzzdetectThreshold() { return getOverride('tooltips.buzzdetectThreshold') ?? "Activation at or above which this neuron counts as detecting"; },
  get buzzdetectAddNeuron() { return getOverride('tooltips.buzzdetectAddNeuron') ?? "Add one of this model's other neurons to the graph"; },
  get buzzdetectNeuronSettings() { return getOverride('tooltips.buzzdetectNeuronSettings') ?? "Color, thresholds, pin, remove"; },
  get buzzdetectSubsetThreshold() { return getOverride('tooltips.buzzdetectSubsetThreshold') ?? "Threshold the subset is cut at.\nLeave blank and this neuron doesn't cut at all; set it lower than the detection threshold to keep the audio around each detection while the graph still marks detections strictly."; },
  get buzzdetectSubsetPick() { return getOverride('tooltips.buzzdetectSubsetPick') ?? "Subset the track by this neuron.\nIn detection-rate mode the cut is judged at the detection threshold and loosened by the minimum rate, so there is no separate value to set."; },
  get buzzdetectSubsetUnpick() { return getOverride('tooltips.buzzdetectSubsetUnpick') ?? "Stop subsetting by this neuron"; },
  get buzzdetectSubsetAbsent() { return getOverride('tooltips.buzzdetectSubsetAbsent') ?? "This track's results have no column for this neuron, so it isn't cutting here.\nClick to drop it from the subset entirely."; },
  get buzzdetectSubsetBuffer() { return getOverride('tooltips.buzzdetectSubsetBuffer') ?? "Seconds of audio kept either side of every subset region, for context around each detection."; },
  get buzzdetectSubset() { return getOverride('tooltips.buzzdetectSubset') ?? "Subset track to detections (Shift+S)"; },
  get importToolsDir() { return getOverride('tooltips.importToolsDir') ?? "Pick a directory of {label}/ folders of audio clips; clips are copied in as examples and tools are created for new labels"; },
  get showAllFiles() { return getOverride('tooltips.showAllFiles') ?? "Showing: all files"; },
  get showingUnannotated() { return getOverride('tooltips.showingUnannotated') ?? "Showing: unannotated only"; },
  get showingAnnotated() { return getOverride('tooltips.showingAnnotated') ?? "Showing: annotated only"; },
  get switchToSorted() { return getOverride('tooltips.switchToSorted') ?? "Enter sorted view"; },
  get shuffleQueue() { return getOverride('tooltips.shuffleQueue') ?? "Enter Shuffle Mode"; },
};
