//! Repo setup (open/init, branch, gitignore), staging + commit, and the
//! local/remote status checks that drive the status-dot indicators.

use std::path::{Path, PathBuf};

use git2::{Repository, Signature};

use crate::commands::shared::{walk_files, ANNOTATION_EXT};

use super::annotate::{annotation_blobs, line_key_set};
use super::{gerr, DEFAULT_BRANCH, REMOTE_NAME};

// ---------------------------------------------------------------------------
// Repo setup
// ---------------------------------------------------------------------------

/// The branch SeeNote syncs on: the repo's current branch when HEAD is born on
/// one, else [`DEFAULT_BRANCH`] (a freshly init'd repo with an unborn HEAD, or a
/// detached HEAD). Using the current branch means dropping SeeNote into an
/// existing repo never switches branches or forks a stray `main`.
pub(crate) fn current_branch(repo: &Repository) -> String {
    if let Ok(head) = repo.head() {
        if head.is_branch() {
            if let Some(name) = head.shorthand() {
                return name.to_string();
            }
        }
    }
    DEFAULT_BRANCH.to_string()
}

/// Point HEAD at `branch` if it isn't already. For an existing repo this is a
/// no-op (`branch` is the current branch by construction); it only acts for a
/// freshly init'd repo whose unborn HEAD defaults to `master`, repointing it so
/// the first commit lands on `branch`. Never switches an existing born branch.
pub(crate) fn ensure_on_branch(repo: &Repository, branch: &str) -> Result<(), String> {
    let already = repo
        .head()
        .ok()
        .filter(|h| h.is_branch())
        .and_then(|h| h.shorthand().map(|s| s == branch))
        .unwrap_or(false);
    if !already {
        repo.set_head(&format!("refs/heads/{branch}")).map_err(gerr)?;
    }
    Ok(())
}

pub(crate) fn open_or_init(project_path: &Path, remote_url: &str) -> Result<Repository, String> {
    let repo = match Repository::open(project_path) {
        Ok(r) => r,
        Err(_) => Repository::init(project_path).map_err(gerr)?,
    };
    // Ensure origin points at the configured URL (idempotent; updates on change).
    match repo.find_remote(REMOTE_NAME) {
        Ok(existing) => {
            if existing.url() != Some(remote_url) {
                repo.remote_set_url(REMOTE_NAME, remote_url).map_err(gerr)?;
            }
        }
        Err(_) => {
            repo.remote(REMOTE_NAME, remote_url).map_err(gerr)?;
        }
    }
    Ok(repo)
}

/// Write gitignores SCOPED to the directories SeeNote owns, so SeeNote can be
/// dropped into an existing repo (full of source code etc.) without disturbing
/// how that repo tracks everything else. We never write a repo-root `.gitignore`.
///
/// Two files:
/// - `<annotationDir>/.gitignore` — within the annotation directory only, track
///   just annotation files ([`ANNOTATION_EXT`]); ignore anything else dropped
///   in there. This is also committed (shared).
/// - `.seenote/.gitignore` — ignore the entire `.seenote/` directory, so the
///   host repo's `git add .` never picks up SeeNote's local state (machine
///   paths, UI, the token, tools). Not committed (it's inside the ignored dir).
pub(crate) fn write_gitignore(project_path: &Path, ann_rel: &Path) -> Result<(), String> {
    let ann_rel_posix = ann_rel.to_string_lossy().replace('\\', "/");
    // Guard the pathological case where the annotation dir IS the repo root —
    // a `*` ignore there would smother the whole repo. Skip it; explicit staging
    // still keeps the commit annotation-only.
    if !ann_rel_posix.is_empty() && ann_rel_posix != "." {
        let ann_dir = project_path.join(ann_rel);
        std::fs::create_dir_all(&ann_dir)
            .map_err(|e| format!("failed to create annotation dir: {e}"))?;
        let content = format!(
            "# Generated by SeeNote. Within this annotation directory, track only\n\
             # annotation files (*.{ext}); ignore anything else.\n\
             *\n\
             !*/\n\
             !*.{ext}\n\
             !.gitignore\n",
            ext = ANNOTATION_EXT,
        );
        std::fs::write(ann_dir.join(".gitignore"), content)
            .map_err(|e| format!("failed to write annotation .gitignore: {e}"))?;
    }

    let seenote_dir = project_path.join(".seenote");
    if seenote_dir.is_dir() {
        std::fs::write(
            seenote_dir.join(".gitignore"),
            "# SeeNote local state — never commit (machine paths, UI, token, tools).\n*\n",
        )
        .map_err(|e| format!("failed to write .seenote/.gitignore: {e}"))?;
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Stage + commit
// ---------------------------------------------------------------------------

/// Stage the curated set explicitly (never `git add .`) and commit if the index
/// differs from HEAD. Returns true if a commit was created.
pub(crate) fn stage_and_commit(
    repo: &Repository,
    project_path: &Path,
    ann_rel: &Path,
    sig: &Signature,
    message: &str,
) -> Result<bool, String> {
    let mut index = repo.index().map_err(gerr)?;

    // HEAD's annotation blobs (path → content), used to skip precision-only
    // rewrites below. Empty when there are no commits yet.
    let head_blobs = match repo.head().ok().and_then(|h| h.peel_to_tree().ok()) {
        Some(tree) => annotation_blobs(repo, &tree)?,
        None => std::collections::HashMap::new(),
    };

    // (a) Annotation files under the annotation directory. Annotation tools are
    //     deliberately NOT synced — each labeler maintains their own tools.
    let ann_abs = project_path.join(ann_rel);
    let mut ann_files: Vec<PathBuf> = Vec::new();
    collect_annotation_files(&ann_abs, &mut ann_files);

    for abs in &ann_files {
        let rel = match abs.strip_prefix(project_path) {
            Ok(r) => r,
            Err(_) => continue,
        };
        let content = std::fs::read_to_string(abs).unwrap_or_default();

        // Fix 2: never commit a 0-byte / whitespace-only annotation file. An
        // empty file is never a legitimate state (the app deletes the file when
        // a track has zero annotations), and the set-merge reads an empty file
        // as "delete every line", truncating the record for every teammate.
        // Skipping it here means such a file is neither staged nor staged for
        // deletion: stage_deletions only removes files ABSENT from disk, and
        // this file exists, so its previously committed content simply stays
        // untouched in HEAD.
        if content.trim().is_empty() {
            continue;
        }

        // Fix 3: skip a precision-only rewrite — the same records re-serialized
        // at a different decimal precision. Comparing canonical record sets (not
        // raw text) means `1.234` vs `1.23400` never creates a commit.
        let rel_posix = rel.to_string_lossy().replace('\\', "/");
        if let Some(head_content) = head_blobs.get(&rel_posix) {
            if line_key_set(&content) == line_key_set(head_content) {
                continue;
            }
        }

        // add_path also picks up modifications; removed files handled below.
        index.add_path(rel).map_err(gerr)?;
    }

    // (b) The annotation directory's own .gitignore (shared). The .seenote
    //     gitignore is intentionally not staged — it lives in the ignored dir.
    if let Ok(rel) = project_path.join(ann_rel).join(".gitignore").strip_prefix(project_path) {
        index.add_path(rel).map_err(gerr)?;
    }
    // Stage deletions of previously-tracked annotation files that no longer
    // exist on disk, so a deleted recording's labels propagate.
    stage_deletions(repo, &mut index, project_path, ann_rel)?;

    // Untrack anything previously committed under .seenote/ — older versions of
    // SeeNote synced tool definitions there; tools are no longer shared. The
    // files stay on disk (now gitignored) but drop out of the next commit.
    let seenote_tracked: Vec<PathBuf> = (0..index.len())
        .filter_map(|i| index.get(i))
        .map(|e| String::from_utf8_lossy(&e.path).into_owned())
        .filter(|p| p.starts_with(".seenote/"))
        .map(PathBuf::from)
        .collect();
    for p in seenote_tracked {
        let _ = index.remove_path(&p);
    }

    index.write().map_err(gerr)?;
    let tree_oid = index.write_tree().map_err(gerr)?;
    let tree = repo.find_tree(tree_oid).map_err(gerr)?;

    let parent = repo.head().ok().and_then(|h| h.peel_to_commit().ok());

    // Skip empty commits.
    if let Some(p) = &parent {
        if p.tree_id() == tree_oid {
            return Ok(false);
        }
    } else if tree.is_empty() {
        return Ok(false);
    }

    let parents: Vec<&git2::Commit> = parent.iter().collect();
    repo.commit(
        Some("HEAD"),
        sig,
        sig,
        message,
        &tree,
        &parents,
    )
    .map_err(gerr)?;
    Ok(true)
}

/// Mark for removal any currently-tracked annotation file that no longer exists
/// in the working tree (an intentional deletion to propagate).
fn stage_deletions(
    repo: &Repository,
    index: &mut git2::Index,
    project_path: &Path,
    ann_rel: &Path,
) -> Result<(), String> {
    let head_tree = match repo.head().ok().and_then(|h| h.peel_to_tree().ok()) {
        Some(t) => t,
        None => return Ok(()), // no commits yet
    };
    let ann_rel_posix = ann_rel.to_string_lossy().replace('\\', "/");
    let mut to_remove: Vec<PathBuf> = Vec::new();
    head_tree
        .walk(git2::TreeWalkMode::PreOrder, |dir, entry| {
            if entry.kind() != Some(git2::ObjectType::Blob) {
                return git2::TreeWalkResult::Ok;
            }
            let name = match entry.name() {
                Some(n) => n,
                None => return git2::TreeWalkResult::Ok,
            };
            let rel = format!("{dir}{name}");
            let is_annotation = rel.starts_with(&ann_rel_posix)
                && rel.ends_with(&format!(".{ANNOTATION_EXT}"));
            if is_annotation && !project_path.join(&rel).exists() {
                to_remove.push(PathBuf::from(&rel));
            }
            git2::TreeWalkResult::Ok
        })
        .map_err(gerr)?;
    for rel in to_remove {
        let _ = index.remove_path(&rel);
    }
    Ok(())
}

fn collect_annotation_files(dir: &Path, out: &mut Vec<PathBuf>) {
    walk_files(dir, &mut |p| {
        if p.extension().and_then(|e| e.to_str()) == Some(ANNOTATION_EXT) {
            out.push(p.to_path_buf());
        }
    });
}

// ---------------------------------------------------------------------------
// Status checks
// ---------------------------------------------------------------------------

/// True if the remote tracking branch has commits not present in HEAD.
pub(crate) fn remote_is_ahead(repo: &Repository, branch: &str) -> Result<bool, String> {
    let remote_ref = format!("refs/remotes/{REMOTE_NAME}/{branch}");
    let remote_oid = match repo.refname_to_id(&remote_ref) {
        Ok(oid) => oid,
        Err(_) => return Ok(false),
    };
    let head_oid = match repo.head().ok().and_then(|h| h.target()) {
        Some(oid) => oid,
        None => return Ok(true), // remote has commits but we have none
    };
    if remote_oid == head_oid {
        return Ok(false);
    }
    let (_, behind) = repo.graph_ahead_behind(head_oid, remote_oid).map_err(gerr)?;
    Ok(behind > 0)
}

/// True if annotation files on disk differ from HEAD, or HEAD is ahead of the
/// remote tracking branch (unpushed commits).
pub(crate) fn has_local_annotation_changes(
    repo: &Repository,
    project_path: &Path,
    ann_rel: &Path,
) -> Result<bool, String> {
    // Check if HEAD is ahead of remote tracking branch (unpushed commits).
    let branch = current_branch(repo);
    let remote_ref = format!("refs/remotes/{REMOTE_NAME}/{branch}");
    if let Ok(remote_oid) = repo.refname_to_id(&remote_ref) {
        if let Some(head_oid) = repo.head().ok().and_then(|h| h.target()) {
            if head_oid != remote_oid {
                if let Ok((ahead, _)) = repo.graph_ahead_behind(head_oid, remote_oid) {
                    if ahead > 0 {
                        return Ok(true);
                    }
                }
            }
        }
    }

    // Compare annotation files on disk to HEAD blobs.
    let ann_abs = project_path.join(ann_rel);
    let head_blobs = match repo.head().ok().and_then(|h| h.peel_to_tree().ok()) {
        Some(tree) => annotation_blobs(repo, &tree)?,
        None => {
            // No commits yet — any annotation file counts as a local change.
            let mut found = false;
            walk_files(&ann_abs, &mut |p| {
                if p.extension().and_then(|e| e.to_str()) == Some(ANNOTATION_EXT) {
                    found = true;
                }
            });
            return Ok(found);
        }
    };

    let mut disk: std::collections::HashMap<String, String> = std::collections::HashMap::new();
    walk_files(&ann_abs, &mut |p| {
        if p.extension().and_then(|e| e.to_str()) != Some(ANNOTATION_EXT) {
            return;
        }
        if let Ok(rel) = p.strip_prefix(project_path) {
            let key = rel.to_string_lossy().replace('\\', "/");
            if let Ok(content) = std::fs::read_to_string(p) {
                disk.insert(key, content);
            }
        }
    });

    // Compare by canonical record set, not raw text, so a precision-only
    // rewrite (same times re-serialized at a different decimal precision) does
    // not read as a local change and light the status dot.
    for (path, content) in &disk {
        match head_blobs.get(path.as_str()) {
            Some(head_content) if line_key_set(content) == line_key_set(head_content) => {}
            _ => return Ok(true),
        }
    }

    let ann_rel_posix = ann_rel.to_string_lossy().replace('\\', "/");
    for path in head_blobs.keys() {
        if path.starts_with(&ann_rel_posix) && !disk.contains_key(path.as_str()) {
            return Ok(true); // deleted on disk
        }
    }

    Ok(false)
}

// ---------------------------------------------------------------------------
// Tests — staging/commit invariants against a real (tempdir) git repo.
// Imitates the tempdir pattern in commands/filesystem.rs.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use git2::Repository;
    use std::path::PathBuf;

    fn make_tmp_root(tag: &str) -> PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_nanos())
            .unwrap_or(0);
        let pid = std::process::id();
        let root = std::env::temp_dir().join(format!("seenote_git_test_{tag}_{pid}_{nanos}"));
        std::fs::create_dir_all(&root).expect("create tmp root");
        root
    }

    /// Init a repo with an `ann` annotation dir and its .gitignore in place.
    fn init_repo(tag: &str) -> (Repository, PathBuf, PathBuf) {
        let root = make_tmp_root(tag);
        let repo = Repository::init(&root).expect("init repo");
        let ann_rel = PathBuf::from("ann");
        write_gitignore(&root, &ann_rel).expect("write gitignore");
        (repo, root, ann_rel)
    }

    fn sig() -> Signature<'static> {
        Signature::now("Tester", "tester@seenote.local").unwrap()
    }

    fn write_ann(root: &Path, name: &str, content: &str) {
        std::fs::write(root.join("ann").join(name), content).unwrap();
    }

    fn head_blob(repo: &Repository, rel: &str) -> Option<String> {
        let tree = repo.head().ok()?.peel_to_tree().ok()?;
        let entry = tree.get_path(Path::new(rel)).ok()?;
        let blob = repo.find_blob(entry.id()).ok()?;
        Some(String::from_utf8_lossy(blob.content()).to_string())
    }

    #[test]
    fn first_commit_stages_annotation_file() {
        let (repo, root, ann_rel) = init_repo("first");
        write_ann(&root, "a.txt", "1.0\t2.0\ta\n");
        let committed = stage_and_commit(&repo, &root, &ann_rel, &sig(), "m").unwrap();
        assert!(committed);
        assert_eq!(head_blob(&repo, "ann/a.txt").as_deref(), Some("1.0\t2.0\ta\n"));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn empty_file_neither_commits_nor_deletes_head_content() {
        let (repo, root, ann_rel) = init_repo("empty");
        write_ann(&root, "a.txt", "1.0\t2.0\ta\n");
        stage_and_commit(&repo, &root, &ann_rel, &sig(), "m").unwrap();

        // Overwrite with whitespace-only content. Must NOT create a commit, and
        // the previously committed content must survive in HEAD (Fix 2).
        write_ann(&root, "a.txt", "   \n\n");
        let committed = stage_and_commit(&repo, &root, &ann_rel, &sig(), "m2").unwrap();
        assert!(!committed, "empty file should not create a commit");
        assert_eq!(head_blob(&repo, "ann/a.txt").as_deref(), Some("1.0\t2.0\ta\n"));
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn precision_only_rewrite_does_not_commit() {
        let (repo, root, ann_rel) = init_repo("precision");
        write_ann(&root, "a.txt", "1.234\t2.5\ta\n");
        stage_and_commit(&repo, &root, &ann_rel, &sig(), "m").unwrap();

        // Re-serialize the same record at more decimals (Fix 3).
        write_ann(&root, "a.txt", "1.23400\t2.50000\ta\n");
        let committed = stage_and_commit(&repo, &root, &ann_rel, &sig(), "m2").unwrap();
        assert!(!committed, "precision-only rewrite should not create a commit");
        assert_eq!(head_blob(&repo, "ann/a.txt").as_deref(), Some("1.234\t2.5\ta\n"));

        // And a genuine change still commits.
        write_ann(&root, "a.txt", "1.234\t2.5\ta\n3.0\t4.0\tb\n");
        assert!(stage_and_commit(&repo, &root, &ann_rel, &sig(), "m3").unwrap());
        std::fs::remove_dir_all(&root).ok();
    }

    #[test]
    fn local_changes_ignores_precision_rewrite() {
        let (repo, root, ann_rel) = init_repo("localdot");
        write_ann(&root, "a.txt", "1.234\t2.5\ta\n");
        stage_and_commit(&repo, &root, &ann_rel, &sig(), "m").unwrap();

        write_ann(&root, "a.txt", "1.23400\t2.50000\ta\n");
        assert!(!has_local_annotation_changes(&repo, &root, &ann_rel).unwrap());

        write_ann(&root, "a.txt", "1.234\t2.5\ta\n9.0\t9.5\tz\n");
        assert!(has_local_annotation_changes(&repo, &root, &ann_rel).unwrap());
        std::fs::remove_dir_all(&root).ok();
    }
}
