---
title: "buzzdetect Classification Dictionary"
---

## Overview

This page catalogues the classification labels we at the OSU Bee Lab use for annotating our [buzzdetect](https://github.com/OSU-Bee-Lab/buzzdetect) training data. SeeNote doesn't require you to use these labels (though it does packages some of them as the default annotation tools), but you might find it a useful starting place for building your own labels or understanding buzzdetect result files.

Labels are hierarchical, with each level divided by an underscore. For example, `ins_buzz_medium` has three levels: the insect sound level, the buzz level, and the pitch level. We organize labels by their rank on this page.

We have chosen to err on the side of specificity in our classifications.
We do this for two reasons. Firstly, we find that our models perform
better (that is, more sensitive and more specific buzz detection)
with more classes, despite smaller training volume per-class. Second,
it's trivial to merge classifications in training data after the
fact, but it's impossible to split a classification without manual
relabeling of files. For example, we usually merge mech_auto_truck and mech_auto_car together when it comes time to train, but we still label them separately.


## ins

All insect-produced sounds: flight buzzes, chirps, timballing, etc.

### ins_buzz

The buzzing hum of insect flight.

Pitches are distinguished by comparison to [reference audio](https://www.youtube.com/watch?v=5HHGDi6HN9c)./
Note that in this video, yellowjackets can often be heard as a slightly lower-pitched buzz; you can usually see them in the video at the same time.

#### LABEL: `ins_buzz_medium` (similar to honey bee)

Insect flight buzzes that sound similar in pitch to honey bee (*Apis mellifera*) flight.


#### LABEL: `ins_buzz_high` (high-pitched buzz)

Flight buzzes that are higher in pitch than that of the honey bee.
Perhaps small solitary bees, flies.

#### LABEL: `ins_buzz_low` (low-pitched buzz)

Flight buzzes that are lower in pitch than that of the honey bee.
Perhaps bumble bees, carpenter bees.

### ins_trill

#### LABEL: `ins_trill`

Chirping or tymbaling as of crickets, cicadas, katydids.
Sometimes so loud as to distort the audio, sometimes far away and droning.

## animal

All sounds produced by non-insect, non-human animals.

#### LABEL: `animal_bird`

Any bird calls. Geese, redtailed hawks, etc.
Currently, we don't attempt to identify birds, so they're all in one label.

### LABEL: `animal_frog`

All frog-produced sounds. Pickerel frogs, tree frogs, bull frogs, spring peepers, etc.
Currently, we don't attempt to identify frogs, so they're all in one label.

## human

#### LABEL: `human`

Human vocalizations - talking, laughing, etc.
Sounds made by humans that aren't vocalization (e.g., walking by the recorders) should not be labeled as human.

## mech

All noises produced by machinery.

### mech_plane

All flying vehicles

#### LABEL: `mech_plane_prop`

The hum of a propeller plane in flight.

#### LABEL: `mech_plane_jet`

Passenger jet planes, F-15s, etc.

### mech_auto

All ground-based vehicles.

#### LABEL: `mech_auto_truck`

The roar of a large truck passing nearby, distant sounds of downshifting,
the low rumble of a diesel engine.

#### LABEL: `mech_auto_car`

The whoosh of a passing car, an engine accelerating onto the main road,
street racers at night.

#### LABEL: `mech_auto_bike`

Motorcycles. The rumble of a chopper, the whine of a sports bike revving.

### others

#### LABEL: `mech_combine`

The persistent, mechanical drone of a combine harvester (or other heavy
farm equipment) in operation. Consistent sounds of the engine,
intermittent sounds of the equipment. May vary in pitch or modulate with
the activation of machinery.

#### LABEL: `mech_train`

The whistle of a train or rumble of a train crossing tracks.

#### LABEL: `mech_siren`

The siren of an emergency vehicle.


#### LABEL: `mech_hum_traffic`
Far off, droning, mechanical noises.
Oddly, these have a high tendency to produce false positives.
Pay careful attention.

The sound of distant (usually highway) traffic. Not the sound of engines
or rushing air, but a far off, continuous, fairly high-pitched and
slightly wavering drone. Perhaps sound produced by tires on a concrete
road.

## ambient

Routine environmental sound 

#### LABEL: `ambient_background`

An absence of any particular event.
Usually, this label is inferred by the absence of other labels.

#### LABEL: `ambient_scraping`

The artificially-amplified sound of something scraping over the recorder
or its stake. May be caused by any number of sources, from an animal
passing by to strong winds. Distinct from the normal, gentle rustle of
leaves that should be categorized as ambient_rustle.

#### LABEL: `ambient_rustle`

Sounds of wind swishing leaves; hard wind blowing; fabric swishing; not
sharp and amplified like `ambient_scraping`.

#### LABEL: `ambient_rain`

The pitter patter of raindrops falling.

#### LABEL: `ambient_bang`

Brief, loud, atonal sounds.
A gunshot, a car backfiring, a firework.
