---
title: "Tips for Annotating"
---

## What we label

### `ins_trill`

Sharp, nearby chirping or tymbaling as of crickets, cicadas, katydids.
Note: a distant background of crickets or cicadas should be classified as
ambient.

### `ins_buzz` — insect buzzes

Generally, we label buzzes as "high," "medium," or "low." These
descriptors are relative to the pitch of a honey bee buzz. When you hear
a buzz, compare it to our
[bee reference audio](https://www.youtube.com/watch?v=5HHGDi6HN9c). If
it's in the range of pitches you hear in that video, annotate it as
`ins_buzz_medium`. Otherwise, use `ins_buzz_low` or `ins_buzz_high`.

### `bird_goose`

Goose.

### `frog_tree`

Tree frogs.

### `human`

Human vocalizations. Not non-vocal human activity (e.g. striding through
crops).

### `mech_plane_prop`

The hum of a propeller plane in flight.

### `mech_plane_jet`

The whoosh and scream of a jet plane in flight.

### `mech_auto_truck`

The roar of a large truck passing nearby, distant sounds of downshifting,
the low rumble of a diesel engine.

### `mech_auto_car`

The whoosh of a passing car, an engine accelerating onto the main road,
street racers at night.

### `mech_auto_bike`

The rumble of a chopper, the whine of a sports bike revving.

### `mech_combine`

The persistent, mechanical drone of a combine harvester (or other heavy
farm equipment) in operation. Consistent sounds of the engine,
intermittent sounds of the equipment. May vary in pitch or modulate with
the activation of machinery.

### `mech_train`

The whistle of a train or rumble of a train crossing tracks.

### `mech_siren`

The siren of an emergency vehicle.

### `mech_hum_traffic`

The sound of distant (usually highway) traffic. Not the sound of engines
or rushing air, but a far off, continuous, fairly high-pitched and
slightly wavering drone. Perhaps sound produced by tires on a concrete
road.

### `ambient_day`

The regular background accompaniment of a fine summer's day. Sitting out
in the middle of a field of soybeans reading a good book. May contain:

- Birdsong
- The rustling of leaves

### `ambient_night`

The regular background accompaniment of a quiet summer's night. Laying on
a blanket under the stars. May contain:

- Crickets chirping in the distance (near chirps should be labeled as
  `ins_trill`)
- Frogs peeping in the distance

### `ambient_scraping`

The artificially-amplified sound of something scraping over the recorder
or its stake. May be caused by any number of sources, from an animal
passing by to strong winds. Distinct from the normal, gentle rustle of
leaves that should be categorized as ambient.

### `ambient_rain`

The pitter patter of raindrops falling.

### `ambient_bang`

A gunshot, a car backfiring, a firework.

### `ambient_rustle`

Sounds of wind swishing leaves; hard wind blowing; fabric swishing; not
sharp and amplified like `ambient_scraping`.

### One-off sounds

It's important to label them, because anything not labeled will be
interpreted as background noise.

## What we don't label

### Bird calls

These are too frequent and varied.

### Ambient noise

Any sections of the track that don't have an annotation will still be
included in the training dataset, but they will be interpreted as
ambient background noise. Thus, it's really important to make sure all
relevant events are annotated. If a buzz makes it into the
`ambient_background` label, it will be highly destructive to training.
